import { describe, it, expect } from 'vitest';
import { generateCandidatePool, selectBalancedPlan, generateFilePrompt } from '../../server/planner';
import type { ContentAnalysis } from '../../server/planner';
import { MonthlyPlanSchema, TopicSchema } from '@nacianilcom/content-core';

const SAMPLE_ANALYSIS: ContentAnalysis = {
  series: [
    { slug: 'yazilimda-temel-kavramlar', title: 'Yazılımda Temel Kavramlar', articleCount: 3, publishedCount: 3, categories: ['engineering'], tags: ['basics'] },
    { slug: 'frontend-dersleri', title: 'Frontend Dersleri', articleCount: 2, publishedCount: 1, categories: ['frontend'], tags: ['react', 'css'] },
  ],
  backlogCount: 5,
  categoryDistribution: { engineering: 3, frontend: 2 },
  tagDistribution: { basics: 3, react: 2 },
  publishedThisYear: 4,
};

describe('generateCandidatePool', () => {
  it('generates at least 25 candidates', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    expect(pool.length).toBeGreaterThanOrEqual(2); // at least series continuations
    expect(pool.length).toBeLessThanOrEqual(40);
  });

  it('every candidate passes TopicSchema', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    for (const topic of pool) {
      const result = TopicSchema.safeParse(topic);
      if (!result.success) {
        console.error('Topic failed schema:', topic.title, result.error.message);
      }
      expect(result.success).toBe(true);
    }
  });

  it('includes series continuation topics', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    const hasSeries = pool.some(t => t.seriesFit === 'yazilimda-temel-kavramlar' || t.seriesFit === 'frontend-dersleri');
    expect(hasSeries).toBe(true);
  });

  it('includes user note topics when notes provided', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '- TypeScript generics deep dive\n- GraphQL subscriptions');
    const userTopics = pool.filter(t => t.angle === 'Kullanıcı notundan');
    expect(userTopics.length).toBeGreaterThan(0);
  });
});

describe('selectBalancedPlan', () => {
  it('returns at most targetCount topics', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    const selected = selectBalancedPlan(pool, 10);
    expect(selected.length).toBeLessThanOrEqual(10);
  });

  it('every selected topic passes TopicSchema', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    const selected = selectBalancedPlan(pool, 5);
    for (const topic of selected) {
      const result = TopicSchema.safeParse(topic);
      expect(result.success).toBe(true);
    }
  });

  it('all selected topics have suggestedPublishWeek 1-4', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    const selected = selectBalancedPlan(pool, 8);
    for (const t of selected) {
      expect(t.suggestedPublishWeek).toBeGreaterThanOrEqual(1);
      expect(t.suggestedPublishWeek).toBeLessThanOrEqual(4);
    }
  });

  it('returns empty array for empty pool', () => {
    expect(selectBalancedPlan([], 10)).toHaveLength(0);
  });
});

describe('generateFilePrompt', () => {
  it('returns a non-empty prompt string', () => {
    const prompt = generateFilePrompt(SAMPLE_ANALYSIS, '2026-07', 'some notes');
    expect(typeof prompt).toBe('string');
    expect(prompt.length).toBeGreaterThan(200);
  });

  it('prompt contains target month', () => {
    const prompt = generateFilePrompt(SAMPLE_ANALYSIS, '2026-07', '');
    expect(prompt).toContain('2026-07');
  });

  it('prompt contains inbox routing instructions', () => {
    const prompt = generateFilePrompt(SAMPLE_ANALYSIS, '2026-07', '');
    expect(prompt).toContain('monthlyPlan');
  });

  it('prompt includes sourceBasis requirement', () => {
    const prompt = generateFilePrompt(SAMPLE_ANALYSIS, '2026-07', '');
    expect(prompt).toContain('sourceBasis');
  });
});

describe('MonthlyPlanSchema (file-mode import)', () => {
  it('validates a plan generated by generateCandidatePool + selectBalancedPlan', () => {
    const pool = generateCandidatePool(SAMPLE_ANALYSIS, '');
    const selected = selectBalancedPlan(pool, 4);
    const plan = {
      month: '2026-07',
      targetCount: 10,
      candidatePool: pool,
      selected,
      status: 'draft' as const,
      userDecisions: [],
    };
    const result = MonthlyPlanSchema.safeParse(plan);
    if (!result.success) console.error('Plan schema error:', result.error.message);
    expect(result.success).toBe(true);
  });

  it('validates minimal plan with empty arrays', () => {
    const plan = {
      month: '2026-07',
      targetCount: 10,
      candidatePool: [],
      selected: [],
      status: 'draft' as const,
      userDecisions: [],
    };
    expect(MonthlyPlanSchema.safeParse(plan).success).toBe(true);
  });
});
