const PUBLIC_DOCUMENT_PREFIXES = [
  'sources/8-sertifikalar/',
  'sources/7-diploma/',
] as const;

export interface ResumeDocumentAssets {
  pdfUrl: string;
  previewUrl: string;
}

/** Web paths for resume PDF + preview image (generated by scripts/generate-credential-previews.mjs). */
export function resumeDocumentAssets(item: {
  id: string;
  sourcePath?: string | undefined;
}): ResumeDocumentAssets | null {
  if (!item.sourcePath) return null;
  if (!PUBLIC_DOCUMENT_PREFIXES.some((prefix) => item.sourcePath!.startsWith(prefix))) return null;
  return {
    pdfUrl: `/credentials/${item.id}.pdf`,
    previewUrl: `/credentials/previews/${item.id}.webp`,
  };
}

/** @deprecated use resumeDocumentAssets */
export const credentialAssets = resumeDocumentAssets;

export function resumeDocumentPdfFilename(title: string): string {
  const safe = title
    .replace(/[^\w\s\-().,]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 80);
  return `${safe || 'document'}.pdf`;
}

/** @deprecated use resumeDocumentPdfFilename */
export function credentialPdfFilename(item: { title: string }): string {
  return resumeDocumentPdfFilename(item.title);
}
