import type { Credential } from '@nacianilcom/content-core';

const PUBLIC_CERT_PREFIX = 'sources/8-sertifikalar/';

export interface CredentialAssets {
  pdfUrl: string;
  previewUrl: string;
}

/** Web paths for certificate PDF + preview image (generated by scripts/generate-credential-previews.mjs). */
export function credentialAssets(cred: Pick<Credential, 'id' | 'sourcePath'>): CredentialAssets | null {
  if (!cred.sourcePath?.startsWith(PUBLIC_CERT_PREFIX)) return null;
  return {
    pdfUrl: `/credentials/${cred.id}.pdf`,
    previewUrl: `/credentials/previews/${cred.id}.webp`,
  };
}

export function credentialPdfFilename(cred: Pick<Credential, 'title'>): string {
  const safe = cred.title
    .replace(/[^\w\s\-().,]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 80);
  return `${safe || 'certificate'}.pdf`;
}
